# Generated by Django 4.0.6 on 2022-09-04 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsportal', '0003_usercategory_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategory',
            unique_together={('user', 'category')},
        ),
    ]
