# Generated by Django 4.0.6 on 2022-08-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_tag_remove_post_category_post_tags_and_more'),
        ('newsportal', '0003_alter_author_user'),
    ]

    operations = [
    ]
